name: Build
on: [push, pull_request]
jobs:

  quality-check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: [ '1.12', '1.13', '1.14', '1.15' ]
    name: Go ${{ matrix.go }} Quality Checks

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: fmt
        id: go-fmt
        run: go fmt ./...

      - name: vet
        id: go-vet
        run: go vet ./...

      - name: build
        id: go-build
        run: go build -v .

  unit-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: [ '1.12', '1.13', '1.14', '1.15' ]
    name: Go ${{ matrix.go }} Unit Tests

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Test
        id: test
        run: go test -v ./...
      
      # TODO add codecov.io

  integration-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: [ '1.12', '1.13', '1.14', '1.15' ]
    name: Go ${{ matrix.go }} Integration Tests

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: setup-gremlin
        id: setup
        run: docker run -d -p 8182:8182 tinkerpop/gremlin-server

      - name: add-vertex
        working-directory: examples/add-vertex
        id: add-vertex-example
        run: go run main.go -h ws://127.0.0.1:8182

      - name: add-vertex-by-api
        working-directory: examples/add-vertex-by-api
        id: add-vertex-by-api-example
        run: go run main.go -h ws://127.0.0.1:8182

      - name: add-vertex-by-query
        working-directory: examples/add-vertex-by-query
        id: add-vertex-by-query-example
        run: go run main.go -h ws://127.0.0.1:8182

      - name: add-vertex-by-string
        working-directory: examples/add-vertex-by-string
        id: add-vertex-by-string-example
        run: go run main.go -h ws://127.0.0.1:8182

      - name: add-vertex-by-struct
        working-directory: examples/add-vertex-by-struct
        id: add-vertex-by-struct-example
        run: go run main.go -h ws://127.0.0.1:8182

      - name: all-vertices
        working-directory: examples/all-vertices
        id: all-vertices-example
        run: go run main.go -h ws://127.0.0.1:8182

      - name: auth-example
        working-directory: examples/auth-example
        id: auth-example
        run: go run main.go -h ws://127.0.0.1:8182

      - name: vertex-properties-example
        working-directory: examples/vertex-properties-example
        id: vertex-properties-example
        run: go run main.go -h ws://127.0.0.1:8182
